# Generated by Django 4.2.2 on 2023-06-25 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='id_tipoArticulo',
            field=models.ForeignKey(db_column='idTipoArticulo', default=0, on_delete=django.db.models.deletion.CASCADE, to='index.tipoarticulo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_tipoMascota',
            field=models.ForeignKey(db_column='idTipoMascota', default=0, on_delete=django.db.models.deletion.CASCADE, to='index.tipomascota'),
        ),
    ]
