# Generated by Django 4.2.2 on 2023-06-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_producto_id_tipoarticulo_producto_id_tipomascota'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='usuario_var',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
